=== Nikhil85/freeswitch-scxml/server/fsadapter-lib/src/main/resources/scxml/scxml.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.w3.org/2005/07/scxml" xmlns="http://www.w3.org/2005/07/scxml">
	<xsd:annotation>
		<xsd:documentation>State Chart XML Schema (20060118)
		</xsd:documentation>
	</xsd:annotation>
	<xsd:annotation>
		<xsd:documentation>
			Copyright 1998-2006 W3C (MIT, ERCIM, Keio), All Rights Reserved. 
			Permission to use, copy, modify and distribute the VoiceXML schema 
			and its accompanying documentation for any purpose and without fee 
			is hereby granted in perpetuity, provided that the above copyright 
			notice and this paragraph appear in all copies. The copyright 
			holders make no representation about the suitability of the schema 
			for any purpose. It is provided "as is" without expressed or implied
			warranty.
        </xsd:documentation>
	</xsd:annotation>
	<xsd:element name="scxml">
		<xsd:complexType>
			<xsd:choice minOccurs="1" maxOccurs="unbounded">
				<xsd:element ref="datamodel" minOccurs="0" maxOccurs="1" />
				<xsd:element ref="state" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element ref="parallel" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element ref="final" minOccurs="0" maxOccurs="unbounded" />
			</xsd:choice>
			<xsd:attribute name="version" type="xsd:string" fixed="1.0" />
			<xsd:attribute name="initialstate" type="xsd:IDREF"
				use="required" />
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="datamodel">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="data" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="data">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:any processContents="lax" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="src" type="xsd:anyURI" />
			<xsd:attribute name="expr" type="xsd:string" />
			<xsd:attribute name="name" type="xsd:NMTOKEN" use="required" />
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="state">
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element ref="onentry" minOccurs="0" maxOccurs="1" />
				<xsd:element ref="invoke" minOccurs="0" maxOccurs="1" />
				<xsd:element ref="transition" minOccurs="0" />
				<xsd:element ref="initial" minOccurs="0" maxOccurs="1" />
				<xsd:element ref="state" minOccurs="0" />
				<xsd:element ref="history" minOccurs="0" />
				<xsd:element ref="parallel" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element ref="anchor" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element ref="onexit" minOccurs="0" maxOccurs="1" />
				<xsd:element ref="datamodel" minOccurs="0" maxOccurs="1" />
			</xsd:choice>
			<xsd:attribute name="id" type="xsd:ID" use="required" />
			<xsd:attribute name="src" type="xsd:anyURI" />
			<xsd:attribute name="final" type="xsd:boolean" />
			<xsd:attribute name="task" type="xsd:boolean" />
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="initial">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="transition" minOccurs="1" maxOccurs="1" />
			</xsd:sequence>
			<xsd:attribute name="id" type="xsd:ID" use="optional" />
			<xsd:attribute name="src" type="xsd:anyURI" />
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="onentry">
		<xsd:complexType>
			<xsd:group ref="executablecontent" minOccurs="0" maxOccurs="unbounded" />
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="onexit">
		<xsd:complexType>
			<xsd:group ref="executablecontent" minOccurs="0" maxOccurs="unbounded" />
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="transition">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:group ref="executablecontent" minOccurs="0"
					maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="event" type="xsd:string" />
			<xsd:attribute name="cond" type="xsd:string" />
			<xsd:attribute name="target" type="xsd:IDREF" />
			<xsd:attribute name="anchor" type="NMTOKEN" />
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="invoke">
		<xsd:complexType>
			<xsd:choice>
				<xsd:element ref="param" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element ref="finalize" minOccurs="0" maxOccurs="1" />
				<xsd:element ref="content" minOccurs="0" maxOccurs="1" />
			</xsd:choice>
			<xsd:attribute name="src" type="xsd:anyURI" />
			<xsd:attribute name="srcexpr" type="xsd:string" />
			<xsd:attribute name="targettype" type="targettype" use="required" />
		</xsd:complexType>
		<xsd:choice minOcccurs="0" maxOccurs="unbounded" />
	</xsd:element>
	<xsd:element name="finalize">
		<xsd:complexType>
			<xsd:group ref="executablecontent" minOccurs="0" maxOccurs="unbounded" />
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="content">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:complexType mixed="true"></xsd:complexType>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="parallel">
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element ref="onentry" minOccurs="0" maxOccurs="1" />
				<xsd:element ref="onexit" minOccurs="0" maxOccurs="1" />
				<xsd:element ref="state" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element ref="parallel" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element ref="datamodel" minOccurs="0" maxOccurs="1" />
				<xsd:element ref="join" minOccurs="0" />
			</xsd:choice>
			<xsd:attribute name="id" type="xsd:ID" use="required" />
			<xsd:attribute name="src" type="xsd:anyURI" />
			<xsd:attribute name="task" type="xsd:boolean" />
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="final">
		<xsd:complexType>
			<xsd:attribute name="id" type="xsd:ID" use="optional" />
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="history">
		<xsd:complexType>
			<xsd:sequence minOccurs="1" maxOccurs="1">
				<xsd:element ref="transition" />
			</xsd:sequence>
			<xsd:attribute name="id" type="xsd:ID" use="required" />
			<xsd:attribute name="src" type="xsd:anyURI" />
			<xsd:attribute name="type" type="historytype" />
		</xsd:complexType>
	</xsd:element>
	<!--
		possible values for the 'type' attribute of the 'history' element
	-->
	<xsd:simpleType name="historytype">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="shallow" />
			<xsd:enumeration value="deep" />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:element name="anchor">
		<xsd:complexType>
			<xsd:attribute name="type" type="NMTOKEN" use="required" />
			<xsd:attribute name="snapshot" type="xpathExpr" />
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="param">
		<xsd:complexType>
			<xsd:attribute name="name" type="xsd:Name" use="required" />
			<xsd:attribute name="expr" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>
	<!-- all declarations for executable content go in this group -->
	<!-- those elements are declared after this group -->
	<xsd:group name="executablecontent">
		<xsd:choice>
			<xsd:element ref="assign" minOccurs="0" maxOccurs="unbounded" />
			<xsd:element ref="send" minOccurs="0" maxOccurs="unbounded" />
			<xsd:element ref="event" minOccurs="0" maxOccurs="unbounded" />
			<xsd:element ref="if" minOccurs="0" maxOccurs="unbounded" />
			<xsd:element ref="log" minOccurs="0" maxOccurs="unbounded" />
			<xsd:any minOccurs="0" maxOccurs="unbounded" />
		</xsd:choice>
	</xsd:group>
	<xsd:element name="assign">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:any processContents="lax" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="location" type="xpathExpr" use="required" />
			<xsd:attribute name="src" type="xsd:anyURI" />
			<xsd:attribute name="expr" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="send">
		<xsd:annotation>
			<xsd:documentation source="http://www.w3.org/TR/scxml/#send" />
		</xsd:annotation>
		<xsd:complexType>
			<xsd:attribute name="event" type="xsd:string" />
			<xsd:attribute name="target" type="xsd:anyURI" />
			<xsd:attribute name="targettype" type="xsd:string"
				default="scxml" />
			<xsd:attribute name="sendid" type="xsd:string" />
			<!--
				attention: "xsd:string" is not the proper type for the following
				attribute, rather a string in CSS2 format is required
			-->
			<xsd:attribute name="delay" type="xsd:string" default="'0s'" />
			<xsd:attribute name="namelist" type="xsd:string" />
			<xsd:attribute name="hints" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="if">
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element ref="elseif" />
				<xsd:element ref="else" />
				<xsd:group ref="executablecontent" />
			</xsd:choice>
			<xsd:attribute name="cond" type="xsd:string" use="required" />
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="elseif">
		<xsd:complexType>
			<xsd:choice>
				<xsd:group ref="executablecontent" />
			</xsd:choice>
			<xsd:attribute name="cond" type="xsd:string" use="required" />
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="else">
		<xsd:complexType>
			<xsd:choice>
				<xsd:group ref="executablecontent" />
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="event">
		<xsd:complexType>
			<xsd:attribute name="name" type="NMTOKEN" />
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="log">
		<xsd:complexType>
			<xsd:attribute name="label" type="xsd:string" />
			<xsd:attribute name="expr" type="xsd:string" use="required" />
			<xsd:attribute name="level" type="loglevel" />
		</xsd:complexType>
	</xsd:element>
	<!--
		log levels are TBD; values below are taken from Java Commons Logging
	-->
	<xsd:simpleType name="loglevel">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="trace" />
			<xsd:enumeration value="debug" />
			<xsd:enumeration value="info" />
			<xsd:enumeration value="warn" />
			<xsd:enumeration value="error" />
			<xsd:enumeration value="fatal" />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="xpathExpr">
		<xsd:restriction base="xs:token" />
	</xsd:simpleType>
</xsd:schema>

=== Nikhil85/freeswitch-scxml/server/fsadapter-lib/src/main/resources/scxml/pec.xml
<sc:scxml  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:sc='http://www.w3.org/2005/07/scxml'
   xmlns:ms='http://telmi.se/MS'
   xsi:schemaLocation='
   http://www.w3.org/2005/07/scxml
   scxml.xsd
   http://telmi.se/MS
   telmims.xsd' initialstate="welcome">

    <sc:datamodel>
        <sc:data name="template" expr="'pec.vm'" />
        <sc:data name="action" expr="'SENDMAIL'" />
        <!--Sound Path -->
        <sc:data name="sp" expr="'/usr/local/freeswitch/sounds/pec/'" />
    </sc:datamodel>

    <sc:state id="welcome">
        <sc:onentry>
            <ms:answer />
            <ms:menu
           ms:choices="1"
           maxtime="30s"
           value="sp + 'welcome.wav'" />
        </sc:onentry>

        <sc:transition event="choice:1" target="number" />

        <sc:transition event="maxtime"  target="welcome" cond="count.maxtime lt 3" />
        <sc:transition event="maxtime"  target="exit" cond="count.maxtime == 3" />

        <sc:transition  event="nomatch" target="welcome" cond="count.nomatch lt 3" />
        <sc:transition  event="nomatch" target="exit" cond="count.nomatch == 3" />

    </sc:state>


    <sc:state id="number">

        <sc:onentry>
            <ms:inputdigits
            maxdigits="16"
            mindigits="5"
            value="sp + 'enter-phonenumber.wav'"
            var="phoneNumber"
            timeout="30s"/>
        </sc:onentry>

        <sc:transition event="termdigit"  target="validate" />

        <sc:transition event="maxtime"    target="number" cond="count.maxtime   lt 3" />
        <sc:transition event="mindigits"  target="number" cond="count.mindigits lt 3" />
        <sc:transition event="maxdigits"  target="number" cond="count.maxdigits lt 3"/>
        <sc:transition event="maxtime"    target="exit"   cond="count.maxtime   eq 3" />
        <sc:transition event="mindigits"  target="exit"   cond="count.mindigits eq 3" />
        <sc:transition event="maxdigits"  target="exit"   cond="count.maxdigits eq 3"/>
    </sc:state>

    <sc:state id="validate">

        <sc:onentry>
            <ms:playaudio value="sp +'you-have-entered.wav'" />
            <ms:phrase value="phoneNumber" format="number" method="iterated" />
            <ms:menu value="sp +'is-this-correct.wav'"    ms:choices="19" />
        </sc:onentry>

       <sc:transition event="choice:1" target="sendNumber" />
       <sc:transition event="choice:9" target="number" />

       <sc:transition event="maxtime"  target="validate" cond="count.maxtime lt 3" />
        <sc:transition event="maxtime"  target="exit" cond="count.maxtime == 3" />

        <sc:transition  event="nomatch" target="validate" cond="count.nomatch lt 3" />
        <sc:transition  event="nomatch" target="exit" cond="count.nomatch == 3" />
    </sc:state>

    <sc:state id="sendNumber">
        <sc:onentry>
            <sc:send
            targettype="'basichttp'"
            target="'http://localhost:8080/test'" namelist="template action" />
        </sc:onentry>

        <sc:transition target="exit">
            <ms:playaudio value="sp + 'thanks-for-the-call.wav'" />
        </sc:transition>

    </sc:state>

    <sc:state id="exit" final="true">
        <sc:onentry>
            <ms:hangup/>
        </sc:onentry>
    </sc:state>
</sc:scxml>

=== Nikhil85/freeswitch-scxml/trunk/server/fsadapter-lib/src/main/resources/scxml/extension.xml
<sc:scxml  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:sc='http://www.w3.org/2005/07/scxml'
   xmlns:ms='http://telmi.se/MS'
   xsi:schemaLocation='
   http://www.w3.org/2005/07/scxml
   scxml.xsd
   http://telmi.se/MS
   telmims.xsd' initialstate="welcome">

    <sc:datamodel>
        <sc:data name="sp" expr="'/usr/local/freeswitch/sounds/extension/'" />
        <sc:data name="extensions" expr="3" />
        <sc:data name="choice" expr="'notset'" />
        <sc:data name="answer" expr="true" />
    </sc:datamodel>
    
    <sc:state id="welcome">
        <sc:onentry>
            <ms:answer ms:test="answer" />
            <sc:assign name="answer" expr="false" />
            <ms:menu
           ms:choicesexpr="'1-' + extensions"
           maxtime="30s"
           value="sp + 'main-menu.wav'" />
        </sc:onentry>

        <sc:transition event="match"   target="exit" >
            <sc:assign name="choice" expr="_eventdatamap.match" />
             <sc:log expr="choice" />
        </sc:transition>

        <sc:transition event="maxtime"  target="welcome" cond="count.maxtime lt 3" />
        <sc:transition event="maxtime"  target="exit" cond="count.maxtime == 3" />

        <sc:transition  event="nomatch" target="welcome" cond="count.nomatch lt 3" />
        <sc:transition  event="nomatch" target="exit" cond="count.nomatch == 3" />

    </sc:state>

    <sc:state id="exit" final="true">
        <sc:onentry>
            <ms:exit  namelist="choice" />
        </sc:onentry>
    </sc:state>
</sc:scxml>

=== Nikhil85/freeswitch-scxml/server/fsadapter-lib/src/main/resources/scxml/rest-ivr.xml
<sc:scxml  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:sc='http://www.w3.org/2005/07/scxml'
   xmlns:ms='http://telmi.se/MS'
   xsi:schemaLocation='
   http://www.w3.org/2005/07/scxml
   scxml.xsd
   http://telmi.se/MS
   telmims.xsd' initialstate="welcome">

    <sc:datamodel>
        <sc:data name="action" expr="'RESTAURANTTASK'" />
        <sc:data name="reservationType" expr="'NOTSET'" />
        <sc:data name="reservationPrompt" expr="'NOTSET'" />
        <sc:data name="recordingPrompt" expr="'NOTSET'" />
        <sc:data name="reservationTempus" expr="'NOTSET'" />
        <sc:data name="template" expr="'restaurant-mail.vm'" />
        <sc:data name="fullyBookedFlag" expr="true" />
       <sc:data name="extension" expr="1" />

            <!--Sound Path -->
        <sc:data name="sp" expr="'/usr/local/freeswitch/sounds/rest/'" />

    </sc:datamodel>

    <sc:state id="welcome">
        <sc:onentry>
            <ms:answer />
        </sc:onentry>

        <sc:transition target="main" >
            <ms:playaudio value="sp + 'Welcome.wav'" />
        </sc:transition>

    </sc:state>
    
    <sc:state id="main">

        <sc:onentry>
            <ms:menu
          ms:choices="*1234"
          value="sp + 'MainMenu.wav'"
          ms:termdigits="#"
          maxtime="10s" />
        </sc:onentry>

        <sc:transition event="choice:1" target="reservationTempus">
            <sc:assign name="reservationType"   expr="'RESERVATION'"/>
            <sc:assign name="reservationPrompt" expr="sp + 'GetTempus_MakeReservation.wav'"/>
        </sc:transition>

        <sc:transition event="choice:2" target="reservationTempus">
            <sc:assign name="reservationType" expr="'CANCEL_RESERVATION'"/>
            <sc:assign name="reservationPrompt" expr="sp + 'GetTempus_CancelReservation.wav'"/>
        </sc:transition>

        <sc:transition event="choice:3" target="reservationTempus">
            <sc:assign name="reservationType" expr="'CHANGE_RESERVATION'"/>
            <sc:assign name="reservationPrompt" expr="sp + 'GetTempus_ChangeReservation.wav'"/>
        </sc:transition>

        <sc:transition event="choice:4" target="doTransfer" />

        <sc:transition event="choice:*" target="main" />

        <sc:transition event="hangup"   target="exit" />

        <sc:transition event="maxtime"  target="main" cond="count.maxtime lt 3" />
        <sc:transition event="maxtime"  target="exit" cond="count.maxtime == 3" />

        <sc:transition  event="nomatch" target="main" cond="count.nomatch lt 3" />
        <sc:transition  event="nomatch" target="exit" cond="count.nomatch == 3" />

    </sc:state>
        
    <sc:state id="reservationTempus">

        <sc:onentry>
            <ms:menu ms:choices="*12" value="reservationPrompt"/>
        </sc:onentry>

        <sc:transition event="choice:1" target="recording" cond="fullyBookedFlag eq false" >
            <sc:assign name="reservationTempus" expr="'TODAY'" />

            <sc:if cond="reservationType == 'RESERVATION'">
                <sc:assign name="recordingPrompt" expr="sp + 'GetVM_MakeReservationToday.wav'" />
            </sc:if>

            <sc:if cond="reservationType == 'CANCEL_RESERVATION'">
                <sc:assign name="recordingPrompt" expr="sp + 'GetVM_CancelReservationToday.wav'" />
            </sc:if>

            <sc:if cond="reservationType == 'CHANGE_RESERVATION'">
                <sc:assign name="recordingPrompt" expr="sp + 'GetVM_ChangeReservationToday.wav'" />
            </sc:if>
              
        </sc:transition>

        <sc:transition event="choice:1" target="fullyBooked" cond="fullyBookedFlag eq true" />

        <sc:transition event="choice:2" target="recording">
            <sc:assign name="reservationTempus" expr="'FUTURE'" />

            <sc:if cond="reservationType == 'RESERVATION'">
                <sc:assign name="recordingPrompt" expr="sp + 'GetVM_MakeReservationFuture.wav'" />
            </sc:if>

            <sc:if cond="reservationType == 'CANCEL_RESERVATION'">
                <sc:assign name="recordingPrompt" expr="sp + 'GetVM_CancelReservationFuture.wav'" />
            </sc:if>

            <sc:if cond="reservationType == 'CHANGE_RESERVATION'">
                <sc:assign name="recordingPrompt" expr="sp + 'GetVM_ChangeReservationFuture.wav'" />
            </sc:if>
        </sc:transition>

        <sc:transition event="choice:*" target="main" />

        <sc:transition event="hangup"    target="exit" />

        <sc:transition event="maxtime"  target="reservationTempus" cond="count.maxtime lt 3" />
        <sc:transition event="maxtime"  target="exit" cond="count.maxtime == 3" />

        <sc:transition  event="nomatch" target="reservationTempus" cond="count.nomatch lt 3" />
        <sc:transition  event="nomatch" target="exit" cond="count.nomatch == 3" />

    </sc:state>

    <sc:state id="fullyBooked">
        <sc:onentry>
            <ms:menu
            ms:choices="*2"
            value=" sp + 'FullyBooked.wav'" />
        </sc:onentry>

        <sc:transition target="recording" event="choice:2" >
           <sc:assign name="reservationTempus" expr="'FUTURE'" />
           <sc:assign name="recordingPrompt" expr="sp + 'GetVM_MakeReservationFuture.wav'" />
        </sc:transition>

        <sc:transition event="hangup"    target="exit" />

        <sc:transition event="maxtime"  target="fullyBooked" cond="count.maxtime lt 3" />
        <sc:transition event="maxtime"  target="main" cond="count.maxtime == 3" />

        <sc:transition  event="nomatch" target="fullyBooked" cond="count.nomatch lt 3" />
        <sc:transition  event="nomatch" target="main" cond="count.nomatch == 3" />

    </sc:state>

    <sc:state id="recording" >
      
      <sc:onentry>
           <ms:playaudio value="recordingPrompt" />
           <ms:recordaudio beep="true" maxtime="120s" var="recording" ms:termdigits="#" />
       </sc:onentry>
    
      <sc:transition event="termdigit" target="telephoneNumber" />
      <sc:transition event="maxtime"   target="telephoneNumber" />
      <sc:transition event="hangup"    target="exit" />
    
    </sc:state>


    <sc:state id="telephoneNumber" >

      <sc:onentry>
          <ms:inputdigits var="telephoneNumber" maxdigits="15" mindigits="6" value="sp + 'GetTelephoneNumber.wav'" />
      </sc:onentry>

      <sc:transition event="termdigit" target="submitData" />

      <sc:transition event="maxdigits" target="telephoneNumber" />
      <sc:transition event="mindigits" target="telephoneNumber" />

      <sc:transition event="hangup"    target="exit" />

    </sc:state>


    <sc:state id="submitData" >

        <sc:onentry>
            <sc:send
             targettype="'basichttp'"
             target="'http://localhost:8080/testSubmit/testSubmit'"
             namelist="action template recording reservationType reservationTempus telephoneNumber" />
        </sc:onentry>

     <sc:transition cond="reservationType eq 'RESERVATION'" target="exit" >
         <ms:playaudio value="sp + 'End_MakeReservation.wav'" />
         <ms:playaudio value="sp + 'End_Info.wav'" />
     </sc:transition>

     <sc:transition cond="reservationType eq 'CANCEL_RESERVATION'" target="exit">
         <ms:playaudio value="sp + 'End_ChangeReservation.wav'" />
     </sc:transition>

     <sc:transition cond="reservationType eq 'CHANGE_RESERVATION'" target="exit">
            <ms:playaudio value="sp + 'End_ChangeReservation.wav'" />
            <ms:playaudio value="sp + 'End_Info.wav'" />
     </sc:transition>

    </sc:state>

    <sc:state id="doTransfer">
        <sc:onentry>
            <ms:exit expr="extension" />
        </sc:onentry>
    </sc:state>

    <sc:state id="exit" final="true">
        <sc:onentry>
            <ms:hangup/>
        </sc:onentry>
    </sc:state>

</sc:scxml>
